[project]
name = 'Manufacturing-Equipment-Efficiency'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.machine-registration]
path = 'contracts/machine-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
